-- Apply manually before enabling GCS Slack notifications.
CREATE TABLE IF NOT EXISTS DBD_GCS_NOTIFICATIONS (
    CASE_NUMBER VARCHAR NOT NULL,
    NOTIFICATION_TYPE VARCHAR NOT NULL,
    RECIPIENT_EMAIL VARCHAR,
    NOTIFICATION_SENT BOOLEAN DEFAULT FALSE,
    SLACK_USER_ID VARCHAR,
    ERROR_MESSAGE VARCHAR(1000),
    LAST_ATTEMPT_AT TIMESTAMP_TZ,
    LAST_NOTIFIED_AT TIMESTAMP_TZ,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CASE_NUMBER, NOTIFICATION_TYPE)
);

CREATE TABLE IF NOT EXISTS DBD_GCS_NOTIFICATION_RUNS (
    RUN_ID VARCHAR PRIMARY KEY,
    STARTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_TZ,
    STATUS VARCHAR,
    STATS VARIANT,
    ERROR_MESSAGE VARCHAR(1000)
);
