

[theme]
primaryColor = "#F63366"
backgroundColor = "#0E1117" # Dark background
secondaryBackgroundColor = "#262730"
textColor = "#F8FAFC"      # White text
font = "sans serif"

[server]
port = 3001
fileWatcherType = "none"